### ISSUE TITLE
Feed - Página Principal

### ISSUE THREAD

**Issue by Logan8192** [kornofilo/PortalEstudiantesGIISA#19]
- [x] Wireframe (Sprint-1)

- [x] Creación de Vista (Sprint-3)

- [x] Vista Responsive (Sprint-3)

- [x] Como usuario, deseo poder ver todas publicaciones de la plataforma (ofertas de empleo, eventos y clasificados). (Sprint-3)

- [x] Como usuario, deseo poder dar click a una publicación y que se me muestre más detalles de la misma (Sprint-3)

- [x] QA (Sprint-4)

**Comment by keresp** [comment]
![Menu](https://user-images.githubusercontent.com/48695822/55271291-7a204880-5278-11e9-9120-ebc5a0cabda9.png)

**Comment by keresp** [comment]
![FEED](https://user-images.githubusercontent.com/48695822/55271409-46deb900-527a-11e9-8b97-d77442b11973.png)

**Comment by keresp** [comment]
![FEEDS](https://user-images.githubusercontent.com/48695822/55605096-86a11700-5738-11e9-873c-78e8543a8002.png)
