### ISSUE TITLE
Feed - Bolsa de Trabajo

### ISSUE THREAD

**Issue by Logan8192** [kornofilo/PortalEstudiantesGIISA#21]
- [x] Wireframe (Sprint-2)

- [x]  Diseño de tabla (Sprint-2)

- [x]    Creación de Vista. **Nota: ** El formulario de creación de vacantes deber estar contenido en un modal (Sprint-3)

- [x] Vista Responsive (Sprint-3)

- [x] Como administrador o moderador, deseo poder publicar ofertas de empleo (Sprint-3)

- [x] Como moderador o administrador, deseo contar la opción de actualizar la información de la oferta de empleo o eliminar la publicación. (Sprint-3)

- [x]  Como administrador, deseo que los usuarios con rol de estudiante no puedan crear vacantes (Sprint-3)

- [x] QA (Sprint-4)

**Comment by keresp** [comment]
![BOLSA DE TRABAJO](https://user-images.githubusercontent.com/48695822/55665373-de588480-5803-11e9-8c25-bf064b095127.png)
