### ISSUE TITLE
Feed - Clasificados

### ISSUE THREAD

**Issue by Logan8192** [kornofilo/PortalEstudiantesGIISA#26]
- [x] Wireframe (Sprint-1)

- [x] Diseño de tabla (Sprint-1)

- [x] Creación de Vista (Sprint-2)

- [x] Vista Responsive (Sprint-3)

- [x] Como usuario, deseo poder ver la sección de clasificados (Sprint-2)

- [x] Como usuario, deseo poder ver los artículos en venta o que se estén comprando (Sprint-2)

- [x] Como usuario, deseo poder ver los hospedajes disponibles (Sprint-2)

- [x] Como usuario, deseo poder ver las tutorías que se encuentran disponibles (Sprint-2)

- [x] Como usuario, deseo poder publicar que estoy vendiendo o comprando un artículo (Sprint-2)

- [x] Como usuario, deseo poder publicar que estoy ofertando un hospedaje (Sprint-2)

- [x] Como usuario, deseo poder publicar que estoy ofreciendo tutorías (Sprint-2)

- [x] QA (Sprint-3)

**Comment by keresp** [comment]
![CLASIFICADOS](https://user-images.githubusercontent.com/48695822/55604931-cadfe780-5737-11e9-9e6d-0fd3e2e19a4c.png)

**Comment by keresp** [comment]
![CLASIFICADOS](https://user-images.githubusercontent.com/48695822/55605073-64a79480-5738-11e9-98c0-275147ea97ee.png)

**Comment by keresp** [comment]
![CLASIFICADOS](https://user-images.githubusercontent.com/48695822/55664892-946ba080-57fb-11e9-92e0-b0444b1dd58b.png)

**Comment by keresp** [comment]
![Tutorias](https://user-images.githubusercontent.com/48695822/55678320-2edfe880-58bd-11e9-899f-f93776f1bae7.png)
