### ISSUE TITLE
Panel de Administración - Moderación de Publicaciones

### ISSUE THREAD

**Issue by Logan8192** [kornofilo/PortalEstudiantesGIISA#29]
- [x]  Wireframe (Sprint-2)

- [x] Creación de vista (Sprint-3)

- [x] Vista responsive (Sprint-3)

- [x]  Como administrador o moderador, deseo que se me muestren las publicaciones de clasificados que cuenten con el estado de "En Moderación" (Sprint-3)

- [x]  Como administrador o moderador, deseo que se me muestre el detalle de cada las publicación de clasificados que cuenten con el estado de "En Moderación" (Sprint-3)

- [x] Como administrador o moderador, deseo contar con una opción que me permita aprobar una publicación con el estado de "En Moderación" para que pueda ser vista por todos los usarios del portal estudiantil (Sprint-3).

- [x] Como administrador o moderador, deseo contar con una opción que me permita rechazar una publicación con el estado de "En Moderación" en caso de que esta no coincida con el tipo de publicación o el contenido de la misma sea nociva (Sprint-3).

- [x] QA (Sprint-4)

**Comment by AAlvarez05** [comment]
La vista de la publicación no muestra la vista preliminar
