### ISSUE TITLE
Password Reset - diseño

### ISSUE THREAD

**Issue by kornofilo** [kornofilo/PortalEstudiantesGIISA#4]
![image](https://user-images.githubusercontent.com/4430949/54964533-d6166480-4f3a-11e9-85f7-6bc63d6630d9.png)
Diseño del password reset

**Comment by Evelync22** [comment]
![rRESTABLECER](https://user-images.githubusercontent.com/48699613/54656578-34070000-4a94-11e9-9f37-a3e75f15065f.JPG)
